### ISSUE TITLE
Other API methods?

### ISSUE THREAD

**Issue by wcandillon** [mkb79/freeletics-python#9]
Thank you for doing, this can be very useful to extract training data.
I was wondering if you have a strategy to discover other API endpoints.
For instance if I have an activity that is of type session, I would like to get the details of the intervals that were performed in that session.

**Comment by mkb79** [comment]
@wcandillon 
I does not use Freeletics for some time. I'll discovered the API endpoint in the past using reverse engineering the Android APK and capture the https traffic from my mobile device. 

After the holidays, I'll see if I can find out the right endpoints.

**Comment by mkb79** [comment]
But theoretically you should get the details using the session id with `client.get_performed_activities_by_id`.

**Comment by wcandillon** [comment]
Thanks a lot, unfortunately get_performed_activities_by_id doesn't seem to work for this kind of activity. I will try to see if I can also setup this to guess the endpoints.

**Comment by wcandillon** [comment]
I had missed the documentation at https://github.com/mkb79/freeletics-python/blob/main/docs/source/endpoints.csv
This works great :) thanks a lot :)

**Comment by mkb79** [comment]
> I had missed the documentation at https://github.com/mkb79/freeletics-python/blob/main/docs/source/endpoints.csv This works great :) thanks a lot :)

I extracted these endpoints from the Android APK. I does not know if they are all working.
